- name: get the theme from github
  become: true 
  ansible.builtin.git:
    repo: 'https://github.com/vinceliuice/grub2-themes.git'
    dest: '{{ user_path }}Projects/grub2-themes/'
  tags: grub

- name: run the install script
  become: true
  shell: 'cd {{ user_path }}Projects/grub2-themes/ &&  ./install.sh -t vimix -i color -b'
  tags: grub 
