
- name: Install zsh using dnf
  dnf:
    name: zsh
    state: latest
  become: true
  tags: zsh

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --skip-chsh
  tags: zsh

- name: Make zsh the default shell
  shell: chsh -s $(which zsh)
  become: true
  tags: zsh

- name: Install zsh plugins for auto suggestions
  become: true
  tags: zsh
  dnf:
    name: zsh-autosuggestions
    state: latest 

- name: Install zsh plugin for syntax highlighting
  become: true
  tags: zsh
  dnf:
    name: zsh-syntax-highlighting
    state: latest

- name : clone zsh autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest:  ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags: zsh


- name : clone zsh syntax highlightin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest:  ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  tags: zsh

- name : Clone fast syntax highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zdharma-continuum/fast-syntax-highlighting.git'
    dest:  ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
  tags: zsh

- name: Clone zsh autocomplete
  ansible.builtin.git:
    repo: 'https://github.com/marlonrichert/zsh-autocomplete.git'
    dest:  ~/.oh-my-zsh/custom/plugins/zsh-autocomplete
    depth: 1
  tags: zsh

- name: edit the .zshrc file to update the config
  shell: sed -i 's/plugins=(git)/plugins=(git colored-man-pages zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting zsh-autocomplete)/' /home/adi/.zshrc
  tags: zsh
